[package]
name = "lazy"
version = "0.1.0"
authors = ["GoogleFeud <volen.sl666@gmail.com>"]
edition = "2018"

[dependencies]
parser = { path = "./src/parser" }
errors = { path = "./src/errors" }
type_checker = { path = "./src/type_checker" }